### ISSUE TITLE
open source?

### ISSUE THREAD

**Issue by cAttte** [JohnGrubba/Discord-Nitro-Bruteforcer#1]
hey! are you planning on open-sourcing this very legitimate project of yours? i would love to see its glorious code! after all, publishing sketchy binaries without any source code to a platform specifically tailored for open source software isn't the most sensible thing to do, is it?

**Comment by JohnGrubba** [comment]
I can give you the source code but since not many people have python and all the packages installed i like to put a exe!

**Comment by JohnGrubba** [comment]
But this Versions are very outdated!
I'll give one with proxys!

**Comment by cAttte** [comment]
ok bud
