### ISSUE TITLE
How do I find the codes after It finds?

### ISSUE THREAD

**Issue by Marc863** [JohnGrubba/Discord-Nitro-Bruteforcer#3]
How do I find the codes after It finds?

**Comment by Marc863** [comment]
Never mind I found out

**Comment by JohnGrubba** [comment]
Ok!

**Comment by hericiumvevo** [comment]
does this work? and how

**Comment by JohnGrubba** [comment]
It Sends API requests to the Discord API! Every time different Proxy and different Code! If the API returns Status Code 200 it's a working Code! You can Check out my Code!
