### ISSUE TITLE
How do I find a successful code?

### ISSUE THREAD

**Issue by arjunthosar** [JohnGrubba/Discord-Nitro-Bruteforcer#4]
So when the program finds a successful code, does it auto-stop? If not, how are you supposed to know when it finds a successful code? I'm asking this because I've generated more than 3.1 million codes so far and I'm afraid I might have missed a successful code.

**Comment by JohnGrubba** [comment]
It saves a successful Code in a txt file

**Comment by JohnGrubba** [comment]
If You got one it wont stop But it will save the Code

**Comment by arjunthosar** [comment]
There aren't any txt files though, and I've generated about 6 million codes by now.

**Comment by JohnGrubba** [comment]
Yeah the possibility of finding a code is low! And if there is no txt file you didn't find one! Don't expect to get a nitro code from this!
There are 403.291.461.126.605.635.584.000.000 different Codes! So 6 Million Codes is like nothing! So don't expect to get a code! This Project is just a showcase on how to bruteforce fast and without ratelimit!
