### ISSUE TITLE
Tutorial on how to set it up ?

### ISSUE THREAD

**Issue by MajsterKyblik** [JohnGrubba/Discord-Nitro-Bruteforcer#6]

**Comment by MobCat** [comment]
Download and install python 3.9
pip install threading (I think, I don't remember)
Download both the checker.py and proxies.txt and place them in the same folder.
Then run python checker.py or
python3.9 checker.py
But as far as I can tell though a some of this script isen't working the best soo it may or may not work right / at all..
Also as your trying to brute force something after it is made BUT before it is used, you have an almost 0% chance of it working but its fun to try.
